name: ci-v1

on:
  push:
    branches:
      - 'v1'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dgoudie/me:v1
      -
        name: Send Event to Watchtower
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.WATCHTOWER_URL }}
          headers: '{"authorization": "${{ secrets.WATCHTOWER_AUTHORIZATION }}"}'
